<?php

$nota1 = 7;
$nota2 = 6;
$nota3 = 8;

echo "a 1° nota é: $nota1 <br/>";
if ($nota1 >= 7) {
    echo "aprovado!<br/>";
}else{
    echo "reprovado! <br/>";
}
echo "a 2° nota é: $nota2 <br/>";
if ($nota2 >= 7) {
    echo "aprovado!<br/>";
}else{
    echo "reprovado! <br/>";
}
echo "a 3° nota é: $nota3 <br/>";
if ($nota3 >= 7) {
    echo "aprovado!<br/>";
}else{
    echo "reprovado! <br/>";
}
?>